//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstCrude.Db_Contex
{
    using System;
    using System.Collections.Generic;
    
    public partial class stable
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public string smail { get; set; }
        public int smob { get; set; }
        public string city { get; set; }
    }
}
